AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentConfigurationMetadata:
  DateCreated: '1543116568000'
  DateModified: '1543116568000'
  Description: '2018-11-24'
EnvironmentTier:
  Name: WebServer
  Type: Standard
OptionSettings:
  AWSEBAutoScalingLaunchConfiguration.aws:ec2:vpc:
    AssociatePublicIpAddress: true
  AWSEBLoadBalancerSecurityGroup.aws:ec2:vpc:
    VPCId: vpc-0d03da78bc40b760a
  AWSEBV2LoadBalancerTargetGroup.aws:elasticbeanstalk:environment:process:default:
    HealthCheckPath: /healthcheck
    MatcherHTTPCode: '200'
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    SecurityGroups: sg-0b412f4dd61a927c7
  aws:ec2:vpc:
    Subnets: subnet-05a910ef3933c1213,subnet-00f6597668a4bf243
    ELBSubnets: subnet-05a910ef3933c1213,subnet-00f6597668a4bf243
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: npm start
  aws:elasticbeanstalk:environment:
    LoadBalancerType: application
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:healthreporting:system:
    SystemType: enhanced
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on 64bit
    Amazon Linux/4.7.0
branch-defaults:
  master:
    environment: media-archive-environment
environment-defaults:
  media-archive-environment:
    branch: null
    repository: null
global:
  application_name: media-archive
  default_ec2_keyname: jtschoonhoven
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.7.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: dist/archive.zip
